from database import get_db, init_db

SAMPLE_QUESTIONS = [
    # ============== A1 (30) ==============
    {"level": "A1", "text": "I ___ a student.", "correct": "am", "wrongs": ["is", "be"]},
    {"level": "A1", "text": "She ___ a doctor.", "correct": "is", "wrongs": ["am", "are"]},
    {"level": "A1", "text": "They ___ from Canada.", "correct": "are", "wrongs": ["is", "am"]},
    {"level": "A1", "text": "___ you tired?", "correct": "Are", "wrongs": ["Is", "Am"]},
    {"level": "A1", "text": "He ___ not at home.", "correct": "is", "wrongs": ["are", "am"]},
    {"level": "A1", "text": "___ is my brother.", "correct": "He", "wrongs": ["Him", "His"]},
    {"level": "A1", "text": "This is ___ book.", "correct": "my", "wrongs": ["me", "I"]},
    {"level": "A1", "text": "___ car is red. (it belongs to her)", "correct": "Her", "wrongs": ["She", "Hers"]},
    {"level": "A1", "text": "We like ___ new teacher.", "correct": "our", "wrongs": ["we", "us"]},
    {"level": "A1", "text": "Is this ___ pen? (it belongs to you)", "correct": "your", "wrongs": ["you", "yours"]},
    {"level": "A1", "text": "What is the plural of 'box'?", "correct": "boxes", "wrongs": ["boxs", "boxies"]},
    {"level": "A1", "text": "What is the plural of 'child'?", "correct": "children", "wrongs": ["childs", "childrens"]},
    {"level": "A1", "text": "I have ___ orange.", "correct": "an", "wrongs": ["a", "the"]},
    {"level": "A1", "text": "There is ___ cat in the garden.", "correct": "a", "wrongs": ["an", "the"]},
    {"level": "A1", "text": "She has two ___. (dog)", "correct": "dogs", "wrongs": ["doges", "dogies"]},
    {"level": "A1", "text": "I ___ to school every day.", "correct": "go", "wrongs": ["goes", "going"]},
    {"level": "A1", "text": "He ___ football on Sundays.", "correct": "plays", "wrongs": ["play", "playing"]},
    {"level": "A1", "text": "___ they live in Madrid?", "correct": "Do", "wrongs": ["Does", "Are"]},
    {"level": "A1", "text": "She ___ coffee every morning.", "correct": "drinks", "wrongs": ["drink", "drinking"]},
    {"level": "A1", "text": "We ___ TV in the evening.", "correct": "watch", "wrongs": ["watches", "watching"]},
    {"level": "A1", "text": "The book is ___ the table.", "correct": "on", "wrongs": ["in", "at"]},
    {"level": "A1", "text": "I live ___ Buenos Aires.", "correct": "in", "wrongs": ["on", "at"]},
    {"level": "A1", "text": "___ is my friend Sara. (she is near me)", "correct": "This", "wrongs": ["These", "That"]},
    {"level": "A1", "text": "___ are my shoes. (they are near me)", "correct": "These", "wrongs": ["This", "That"]},
    {"level": "A1", "text": "The party is ___ Friday.", "correct": "on", "wrongs": ["in", "at"]},
    {"level": "A1", "text": "What color is a banana?", "correct": "yellow", "wrongs": ["blue", "purple"]},
    {"level": "A1", "text": "How many days are there in a week?", "correct": "seven", "wrongs": ["five", "ten"]},
    {"level": "A1", "text": "What do we call your mother's sister?", "correct": "aunt", "wrongs": ["cousin", "niece"]},
    {"level": "A1", "text": "What is the opposite of 'hot'?", "correct": "cold", "wrongs": ["warm", "dry"]},
    {"level": "A1", "text": "What day comes after Monday?", "correct": "Tuesday", "wrongs": ["Sunday", "Wednesday"]},
    # ============== A2 (30) ==============
    {"level": "A2", "text": "Yesterday, I ___ to the park.", "correct": "went", "wrongs": ["go", "goes"]},
    {"level": "A2", "text": "She ___ her homework last night.", "correct": "did", "wrongs": ["do", "done"]},
    {"level": "A2", "text": "They ___ a movie last weekend.", "correct": "watched", "wrongs": ["watch", "watches"]},
    {"level": "A2", "text": "___ you call me yesterday?", "correct": "Did", "wrongs": ["Do", "Were"]},
    {"level": "A2", "text": "He ___ not go to school on Monday.", "correct": "did", "wrongs": ["does", "was"]},
    {"level": "A2", "text": "This is the ___ movie I've ever seen.", "correct": "best", "wrongs": ["gooder", "more good"]},
    {"level": "A2", "text": "My house is ___ than yours.", "correct": "bigger", "wrongs": ["more big", "biggest"]},
    {"level": "A2", "text": "She is the ___ student in the class.", "correct": "smartest", "wrongs": ["more smart", "smart"]},
    {"level": "A2", "text": "He runs ___ than his brother.", "correct": "faster", "wrongs": ["more fast", "fastest"]},
    {"level": "A2", "text": "This book is ___ interesting than that one.", "correct": "more", "wrongs": ["most", "much"]},
    {"level": "A2", "text": "I ___ visit my grandma this weekend.", "correct": "am going to", "wrongs": ["go to", "going"]},
    {"level": "A2", "text": "She ___ study medicine next year.", "correct": "is going to", "wrongs": ["go to", "goes to"]},
    {"level": "A2", "text": "___ you going to the party tonight?", "correct": "Are", "wrongs": ["Do", "Is"]},
    {"level": "A2", "text": "They ___ travel to Brazil next month.", "correct": "are going to", "wrongs": ["go to", "going"]},
    {"level": "A2", "text": "It ___ rain tomorrow, according to the forecast.", "correct": "is going to", "wrongs": ["go to", "will to"]},
    {"level": "A2", "text": "Look! She ___ in the pool.", "correct": "is swimming", "wrongs": ["swims", "swim"]},
    {"level": "A2", "text": "We ___ dinner right now.", "correct": "are having", "wrongs": ["have", "has"]},
    {"level": "A2", "text": "___ you listening to me?", "correct": "Are", "wrongs": ["Do", "Is"]},
    {"level": "A2", "text": "He ___ his homework at the moment.", "correct": "is doing", "wrongs": ["does", "do"]},
    {"level": "A2", "text": "They ___ a new house at the moment.", "correct": "are building", "wrongs": ["build", "builds"]},
    {"level": "A2", "text": "There isn't ___ milk in the fridge.", "correct": "any", "wrongs": ["some", "a"]},
    {"level": "A2", "text": "I have ___ friends in London.", "correct": "some", "wrongs": ["any", "much"]},
    {"level": "A2", "text": "How ___ money do you have?", "correct": "much", "wrongs": ["many", "a lot"]},
    {"level": "A2", "text": "How ___ books are on the shelf?", "correct": "many", "wrongs": ["much", "a lot"]},
    {"level": "A2", "text": "There are ___ apples on the table.", "correct": "some", "wrongs": ["any", "much"]},
    {"level": "A2", "text": "What is the opposite of 'expensive'?", "correct": "cheap", "wrongs": ["costly", "rich"]},
    {"level": "A2", "text": "What time do you usually wake ___?", "correct": "up", "wrongs": ["on", "in"]},
    {"level": "A2", "text": "Please turn ___ the lights before you leave.", "correct": "off", "wrongs": ["down", "out"]},
    {"level": "A2", "text": "I was born ___ 1998.", "correct": "in", "wrongs": ["on", "at"]},
    {"level": "A2", "text": "The meeting starts ___ 9 a.m.", "correct": "at", "wrongs": ["in", "on"]},
    # ============== B1 (30) ==============
    {"level": "B1", "text": "I ___ never been to Japan.", "correct": "have", "wrongs": ["has", "had"]},
    {"level": "B1", "text": "She ___ just finished her homework.", "correct": "has", "wrongs": ["have", "had"]},
    {"level": "B1", "text": "___ you ever tried sushi?", "correct": "Have", "wrongs": ["Did", "Has"]},
    {"level": "B1", "text": "We ___ lived here for ten years.", "correct": "have", "wrongs": ["has", "had"]},
    {"level": "B1", "text": "He ___ already left the office.", "correct": "has", "wrongs": ["have", "had"]},
    {"level": "B1", "text": "If it rains, I ___ stay home.", "correct": "will", "wrongs": ["would", "had"]},
    {"level": "B1", "text": "If she studies hard, she ___ pass the exam.", "correct": "will", "wrongs": ["would", "had"]},
    {"level": "B1", "text": "If you heat ice, it ___.", "correct": "will melt", "wrongs": ["would melt", "melts will"]},
    {"level": "B1", "text": "She will call you if she ___ time.", "correct": "has", "wrongs": ["will have", "had"]},
    {"level": "B1", "text": "If we leave now, we ___ the train.", "correct": "will catch", "wrongs": ["would catch", "catch will"]},
    {"level": "B1", "text": "You ___ wear a seatbelt in the car.", "correct": "must", "wrongs": ["can", "may"]},
    {"level": "B1", "text": "Students ___ arrive on time for class.", "correct": "should", "wrongs": ["would", "might"]},
    {"level": "B1", "text": "You ___ smoke in this building. It's not allowed.", "correct": "mustn't", "wrongs": ["don't have to", "can"]},
    {"level": "B1", "text": "I ___ finish this report by Friday.", "correct": "have to", "wrongs": ["must to", "has to"]},
    {"level": "B1", "text": "You ___ take an umbrella; it might rain.", "correct": "should", "wrongs": ["must to", "can to"]},
    {"level": "B1", "text": "She has been living here ___ 2015.", "correct": "since", "wrongs": ["for", "from"]},
    {"level": "B1", "text": "I have known him ___ five years.", "correct": "for", "wrongs": ["since", "during"]},
    {"level": "B1", "text": "They have been waiting ___ two hours.", "correct": "for", "wrongs": ["since", "during"]},
    {"level": "B1", "text": "He hasn't called me ___ last week.", "correct": "since", "wrongs": ["for", "from"]},
    {"level": "B1", "text": "We have worked here ___ a long time.", "correct": "for", "wrongs": ["since", "during"]},
    {"level": "B1", "text": "This is the man ___ helped me yesterday.", "correct": "who", "wrongs": ["which", "whom"]},
    {"level": "B1", "text": "The book ___ I read last week was great.", "correct": "that", "wrongs": ["who", "whose"]},
    {"level": "B1", "text": "That's the house ___ I grew up.", "correct": "where", "wrongs": ["which", "who"]},
    {"level": "B1", "text": "She is the woman ___ car was stolen.", "correct": "whose", "wrongs": ["who", "which"]},
    {"level": "B1", "text": "This is the reason ___ I called you.", "correct": "why", "wrongs": ["where", "which"]},
    {"level": "B1", "text": "What does 'to give up' mean?", "correct": "to stop trying", "wrongs": ["to raise something", "to celebrate"]},
    {"level": "B1", "text": "What does 'to look after' mean?", "correct": "to take care of", "wrongs": ["to search for", "to resemble"]},
    {"level": "B1", "text": "What does 'to find out' mean?", "correct": "to discover", "wrongs": ["to lose", "to organize"]},
    {"level": "B1", "text": "What does 'to put off' mean?", "correct": "to postpone", "wrongs": ["to wear", "to remove"]},
    {"level": "B1", "text": "What does 'to run into' mean?", "correct": "to meet by chance", "wrongs": ["to hurry", "to avoid"]},
    # ============== B2 (30) ==============
    {"level": "B2", "text": "If I ___ rich, I would travel the world.", "correct": "were", "wrongs": ["was", "am"]},
    {"level": "B2", "text": "If she had more time, she ___ learn French.", "correct": "would", "wrongs": ["will", "had"]},
    {"level": "B2", "text": "I would help you if I ___ how.", "correct": "knew", "wrongs": ["know", "had known"]},
    {"level": "B2", "text": "If we won the lottery, we ___ buy a house.", "correct": "would", "wrongs": ["will", "had"]},
    {"level": "B2", "text": "What would you do if you ___ a ghost?", "correct": "saw", "wrongs": ["see", "had seen"]},
    {"level": "B2", "text": "By the time we arrived, the movie ___ already started.", "correct": "had already started", "wrongs": ["already started", "has already started"]},
    {"level": "B2", "text": "She ___ finished eating when I called.", "correct": "had already", "wrongs": ["already", "has already"]},
    {"level": "B2", "text": "I ___ never seen snow before that trip.", "correct": "had", "wrongs": ["have", "has"]},
    {"level": "B2", "text": "When I got to the station, the train ___ left.", "correct": "had already", "wrongs": ["already had", "has already"]},
    {"level": "B2", "text": "He realized he ___ forgotten his passport.", "correct": "had", "wrongs": ["has", "have"]},
    {"level": "B2", "text": "The report ___ by the manager before it was published.", "correct": "was reviewed", "wrongs": ["reviewed", "has review"]},
    {"level": "B2", "text": "This bridge ___ in 1930.", "correct": "was built", "wrongs": ["built", "has built"]},
    {"level": "B2", "text": "The letter ___ tomorrow.", "correct": "will be sent", "wrongs": ["will send", "is sent"]},
    {"level": "B2", "text": "Many houses ___ during the storm.", "correct": "were damaged", "wrongs": ["damaged", "had damage"]},
    {"level": "B2", "text": "The film ___ by millions of people.", "correct": "has been watched", "wrongs": ["has watched", "was watch"]},
    {"level": "B2", "text": "She said she ___ tired.", "correct": "was", "wrongs": ["is", "has been"]},
    {"level": "B2", "text": "He told me he ___ the report the day before.", "correct": "had finished", "wrongs": ["finished", "has finished"]},
    {"level": "B2", "text": "They said they ___ come to the party.", "correct": "would", "wrongs": ["will", "can"]},
    {"level": "B2", "text": "She asked if I ___ speak French.", "correct": "could", "wrongs": ["can", "would"]},
    {"level": "B2", "text": "He said he ___ to the gym every day.", "correct": "went", "wrongs": ["goes", "was going"]},
    {"level": "B2", "text": "I wish I ___ more time to study.", "correct": "had", "wrongs": ["have", "would have"]},
    {"level": "B2", "text": "She's not answering; she ___ be asleep.", "correct": "must", "wrongs": ["can", "should"]},
    {"level": "B2", "text": "He isn't here; he ___ have forgotten the meeting.", "correct": "might", "wrongs": ["must to", "can"]},
    {"level": "B2", "text": "I wish it ___ stop raining.", "correct": "would", "wrongs": ["will", "could"]},
    {"level": "B2", "text": "That can't be true; she ___ be joking.", "correct": "must", "wrongs": ["should", "need"]},
    {"level": "B2", "text": "___ being tired, she finished the marathon.", "correct": "Despite", "wrongs": ["Although", "However"]},
    {"level": "B2", "text": "He failed the exam ___ he studied hard.", "correct": "although", "wrongs": ["despite", "because"]},
    {"level": "B2", "text": "What is a synonym for 'reluctant'?", "correct": "unwilling", "wrongs": ["eager", "confident"]},
    {"level": "B2", "text": "What is a synonym for 'furious'?", "correct": "extremely angry", "wrongs": ["slightly annoyed", "very happy"]},
    {"level": "B2", "text": "She was exhausted; ___, she kept working.", "correct": "however", "wrongs": ["although", "despite"]},
    # ============== C1 (30) ==============
    {"level": "C1", "text": "Not only ___ late, but he also forgot the documents.", "correct": "did he arrive", "wrongs": ["he arrived", "he did arrive"]},
    {"level": "C1", "text": "Rarely ___ such dedication in a new employee.", "correct": "have I seen", "wrongs": ["I have seen", "I saw"]},
    {"level": "C1", "text": "Never ___ such a beautiful sunset.", "correct": "have I seen", "wrongs": ["I have seen", "I did see"]},
    {"level": "C1", "text": "No sooner ___ the show started than it began to rain.", "correct": "had", "wrongs": ["did", "has"]},
    {"level": "C1", "text": "Under no circumstances ___ leave the door unlocked.", "correct": "should you", "wrongs": ["you should", "you shouldn't"]},
    {"level": "C1", "text": "Had I known about the meeting, I ___ attended.", "correct": "would have", "wrongs": ["will have", "would"]},
    {"level": "C1", "text": "If she had studied harder, she ___ passed the exam.", "correct": "would have", "wrongs": ["will have", "would"]},
    {"level": "C1", "text": "They would have arrived on time if they ___ left earlier.", "correct": "had", "wrongs": ["would have", "have"]},
    {"level": "C1", "text": "I wouldn't have called you if it ___ urgent.", "correct": "hadn't been", "wrongs": ["wasn't", "hasn't been"]},
    {"level": "C1", "text": "If we had known it would rain, we ___ an umbrella.", "correct": "would have brought", "wrongs": ["would bring", "had brought"]},
    {"level": "C1", "text": "If I hadn't missed the flight, I ___ at home now.", "correct": "would be", "wrongs": ["would have been", "will be"]},
    {"level": "C1", "text": "It's high time you ___ your responsibilities seriously.", "correct": "took", "wrongs": ["take", "will take"]},
    {"level": "C1", "text": "The teacher suggested that he ___ the essay again.", "correct": "rewrite", "wrongs": ["rewrites", "rewrote"]},
    {"level": "C1", "text": "If she were taller, she ___ have made the basketball team years ago.", "correct": "would", "wrongs": ["would have", "had"]},
    {"level": "C1", "text": "I would rather you ___ that.", "correct": "didn't say", "wrongs": ["don't say", "hadn't said"]},
    {"level": "C1", "text": "What does 'to bite the bullet' mean?", "correct": "to accept something difficult", "wrongs": ["to eat quickly", "to argue with someone"]},
    {"level": "C1", "text": "What does 'to cut corners' mean?", "correct": "to do something poorly to save time or money", "wrongs": ["to travel a shorter route", "to cut fabric"]},
    {"level": "C1", "text": "What does 'once in a blue moon' mean?", "correct": "very rarely", "wrongs": ["very often", "every month"]},
    {"level": "C1", "text": "What does 'to hit the nail on the head' mean?", "correct": "to be exactly right", "wrongs": ["to make a mistake", "to work hard"]},
    {"level": "C1", "text": "What does 'to let the cat out of the bag' mean?", "correct": "to reveal a secret", "wrongs": ["to release an animal", "to make a mess"]},
    {"level": "C1", "text": "___ the heavy traffic, we arrived on time.", "correct": "Despite", "wrongs": ["Although", "Because"]},
    {"level": "C1", "text": "She was exhausted; ___, she finished the report.", "correct": "nonetheless", "wrongs": ["because", "so that"]},
    {"level": "C1", "text": "He is highly skilled; ___, he lacks experience.", "correct": "nevertheless", "wrongs": ["therefore", "moreover"]},
    {"level": "C1", "text": "The project failed ___ a lack of funding.", "correct": "due to", "wrongs": ["due", "owing"]},
    {"level": "C1", "text": "___ the fact that he apologized, she was still upset.", "correct": "Despite", "wrongs": ["In spite", "Although"]},
    {"level": "C1", "text": "What is a synonym for 'meticulous'?", "correct": "extremely careful", "wrongs": ["very lazy", "quite fast"]},
    {"level": "C1", "text": "What is a synonym for 'ambiguous'?", "correct": "unclear", "wrongs": ["obvious", "simple"]},
    {"level": "C1", "text": "What is a synonym for 'candid'?", "correct": "honest and direct", "wrongs": ["secretive", "nervous"]},
    {"level": "C1", "text": "What is a synonym for 'lucrative'?", "correct": "profitable", "wrongs": ["expensive", "risky"]},
    {"level": "C1", "text": "What is a synonym for 'concise'?", "correct": "brief and clear", "wrongs": ["very long", "confusing"]},
    # ============== C2 (30) ==============
    {"level": "C2", "text": "___ had she finished speaking than the audience erupted in applause.", "correct": "No sooner", "wrongs": ["No earlier", "Not before"]},
    {"level": "C2", "text": "Only after the meeting ___ the real problem.", "correct": "did we realize", "wrongs": ["we realized", "we did realize"]},
    {"level": "C2", "text": "Little ___ he know what awaited him.", "correct": "did", "wrongs": ["does", "had"]},
    {"level": "C2", "text": "So exhausted ___ that she fell asleep instantly.", "correct": "was she", "wrongs": ["she was", "did she"]},
    {"level": "C2", "text": "Seldom ___ such eloquence displayed in a debate.", "correct": "is", "wrongs": ["does", "has"]},
    {"level": "C2", "text": "___ the storm, the event proceeded as planned.", "correct": "Notwithstanding", "wrongs": ["Despite of", "Although of"]},
    {"level": "C2", "text": "The proposal was rejected; the committee, ___, offered an alternative.", "correct": "whereupon", "wrongs": ["whereas", "whereby"]},
    {"level": "C2", "text": "The results were inconclusive; ___, further research is needed.", "correct": "hence", "wrongs": ["despite", "whereas"]},
    {"level": "C2", "text": "___ the evidence presented, the jury remained unconvinced.", "correct": "Notwithstanding", "wrongs": ["Despite of", "In spite"]},
    {"level": "C2", "text": "The policy was flawed; the government, ___, refused to amend it.", "correct": "nonetheless", "wrongs": ["consequently", "whereby"]},
    {"level": "C2", "text": "What does 'to be at loggerheads' mean?", "correct": "to be in strong disagreement", "wrongs": ["to be very tired", "to work together closely"]},
    {"level": "C2", "text": "What does 'to throw caution to the wind' mean?", "correct": "to take a big risk", "wrongs": ["to be very careful", "to give up"]},
    {"level": "C2", "text": "What does the proverb 'don't count your chickens before they hatch' mean?", "correct": "don't assume success too early", "wrongs": ["save your money", "be patient"]},
    {"level": "C2", "text": "What does 'to read between the lines' mean?", "correct": "to understand the hidden meaning", "wrongs": ["to read very carefully", "to skip parts of a text"]},
    {"level": "C2", "text": "What does 'a blessing in disguise' mean?", "correct": "something good that seemed bad at first", "wrongs": ["a hidden danger", "a lucky coincidence"]},
    {"level": "C2", "text": "What is the meaning of 'ubiquitous'?", "correct": "present everywhere", "wrongs": ["very rare", "extremely large"]},
    {"level": "C2", "text": "What is the meaning of 'ephemeral'?", "correct": "lasting a very short time", "wrongs": ["eternal", "very heavy"]},
    {"level": "C2", "text": "What is the meaning of 'esoteric'?", "correct": "understood by only a few", "wrongs": ["very simple", "widely known"]},
    {"level": "C2", "text": "What is the meaning of 'pragmatic'?", "correct": "practical", "wrongs": ["idealistic", "emotional"]},
    {"level": "C2", "text": "What is the meaning of 'ostensible'?", "correct": "apparent but not necessarily true", "wrongs": ["hidden", "undeniable"]},
    {"level": "C2", "text": "The committee's decision was, to say the ___, controversial.", "correct": "least", "wrongs": ["most", "very"]},
    {"level": "C2", "text": "For a formal report: 'The results ___ a significant improvement.'", "correct": "demonstrate", "wrongs": ["show off", "point at"]},
    {"level": "C2", "text": "Which is the most formal way to say 'get rid of'?", "correct": "eliminate", "wrongs": ["dump", "throw away"]},
    {"level": "C2", "text": "Which is the most formal way to say 'find out'?", "correct": "ascertain", "wrongs": ["figure out", "suss out"]},
    {"level": "C2", "text": "Which word means a firm's formal action to reduce costs?", "correct": "retrench", "wrongs": ["cut back", "slash"]},
    {"level": "C2", "text": "___ can it be argued that the policy was entirely successful.", "correct": "Under no circumstances", "wrongs": ["In no way did", "Not at all"]},
    {"level": "C2", "text": "Were it not for his intervention, the deal ___ collapsed.", "correct": "would have", "wrongs": ["will have", "would"]},
    {"level": "C2", "text": "Such was the intensity of the storm ___ entire roofs were torn off.", "correct": "that", "wrongs": ["which", "so that"]},
    {"level": "C2", "text": "___ she a more experienced negotiator, the outcome might have differed.", "correct": "Were", "wrongs": ["If", "Had"]},
    {"level": "C2", "text": "The findings, ___ compelling, do not fully resolve the debate.", "correct": "while", "wrongs": ["despite", "because"]},
]


def seed():
    init_db()
    conn = get_db()
    existing = conn.execute("SELECT COUNT(*) AS c FROM questions").fetchone()["c"]
    if existing > 0:
        print(f"{existing} questions already loaded. Nothing inserted.")
        conn.close()
        return

    for q in SAMPLE_QUESTIONS:
        cur = conn.execute(
            "INSERT INTO questions (text, level) VALUES (?, ?)", (q["text"], q["level"])
        )
        question_id = cur.lastrowid
        conn.execute(
            "INSERT INTO correct_answers (question_id, text) VALUES (?, ?)",
            (question_id, q["correct"]),
        )
        for w in q["wrongs"]:
            conn.execute(
                "INSERT INTO wrong_answers (question_id, text) VALUES (?, ?)", (question_id, w)
            )
    conn.commit()
    conn.close()
    print(f"Loaded {len(SAMPLE_QUESTIONS)} sample questions.")


if __name__ == "__main__":
    seed()
